#:schema node_modules/wrangler/config-schema.json
name = "copytweet"
main = "src/index.js"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[vars]
TELEGRAM_API_KEY = "BOT_FATHER_API_KEY"
